const process = require('node:process');
const readline = require('node:readline/promises');
const { marked } = require('marked');
const { markedTerminal } = require('marked-terminal');

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout
});
let _CTRL_C_FLAG = false;
rl.on('SIGINT', () => {
  if (_CTRL_C_FLAG) process.exit(0);
  _CTRL_C_FLAG = true;
  setTimeout(() => _CTRL_C_FLAG = false, 2000);
});

marked.use(markedTerminal({
  // <https://github.com/mikaelbr/marked-terminal/tree/7eb3cd342807a87688b9a8788eab54816ed38279?tab=readme-ov-file#options>
  reflowText: true,
  showSectionPrefix: false,
  tab: 2
}));

const terminal = require('./ui/terminal.js');

const CONFIG = {
  projectDirectory: process.env.SLOP_PROJECT_DIR || `${process.env.PWD}/.slop`,

  port: process.env.SLOP_PORT || 11434,
  host: process.env.SLOP_HOST || 'http://127.0.0.1',
  endpoint: process.env.SLOP_ENDPOINT || '/api/chat',
  
  model: process.env.SLOP_MODEL || 'qwen3.5:9b-32k'
};
CONFIG.connection = `${CONFIG.host}:${CONFIG.port}${CONFIG.endpoint}`;

/* Banner */
terminal.Text.color('bold', `
  ██████  ██▓     ▒█████   ██▓███   ▄▄▄        ▄████  ▄▄▄     ▄▄▄█████▓▓█████        ██████  ██░ ██ 
▒██    ▒ ▓██▒    ▒██▒  ██▒▓██░  ██▒▒████▄     ██▒ ▀█▒▒████▄   ▓  ██▒ ▓▒▓█   ▀      ▒██    ▒ ▓██░ ██▒
░ ▓██▄   ▒██░    ▒██░  ██▒▓██░ ██▓▒▒██  ▀█▄  ▒██░▄▄▄░▒██  ▀█▄ ▒ ▓██░ ▒░▒███        ░ ▓██▄   ▒██▀▀██░
  ▒   ██▒▒██░    ▒██   ██░▒██▄█▓▒ ▒░██▄▄▄▄██ ░▓█  ██▓░██▄▄▄▄██░ ▓██▓ ░ ▒▓█  ▄        ▒   ██▒░▓█ ░██ 
▒██████▒▒░██████▒░ ████▓▒░▒██▒ ░  ░ ▓█   ▓██▒░▒▓███▀▒ ▓█   ▓██▒ ▒██▒ ░ ░▒████▒ ██▒ ▒██████▒▒░▓█▒░██▓
▒ ▒▓▒ ▒ ░░ ▒░▓  ░░ ▒░▒░▒░ ▒▓▒░ ░  ░ ▒▒   ▓▒█░ ░▒   ▒  ▒▒   ▓▒█░ ▒ ░░   ░░ ▒░ ░ ▒▓▒ ▒ ▒▓▒ ▒ ░ ▒ ░░▒░▒
░ ░▒  ░ ░░ ░ ▒  ░  ░ ▒ ▒░ ░▒ ░       ▒   ▒▒ ░  ░   ░   ▒   ▒▒ ░   ░     ░ ░  ░ ░▒  ░ ░▒  ░ ░ ▒ ░▒░ ░
░  ░  ░    ░ ░   ░ ░ ░ ▒  ░░         ░   ▒   ░ ░   ░   ░   ▒    ░         ░    ░   ░  ░  ░   ░  ░░ ░
      ░      ░  ░    ░ ░                 ░  ░      ░       ░  ░           ░  ░  ░        ░   ░  ░  ░
                                                                                ░                   
                                         Propagate the slop

`);
terminal.Text.color('system', `Connection: ${CONFIG.connection}`);
terminal.Text.color('system', `Model: ${CONFIG.model}`);
console.log();

/* TODO
 * 1. Load system prompt from one of ~/.slopagate/SYSTEM.md or .slop/SYSTEM.md,
 *    in that order
 * 2. Load project prompts from these places, concatenating results:
 *    - ~/.slopagate/SLOP.md
 *    - .slop/SLOP.md
 *    - SLOP.md
 * 3. ~~Generate chat ID, 16-char random alphanum~~
 * 4. Send system prompt
 */

const ID = () => {
  // SLOP: generated by asking for a "unique identifier like a guid"
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    let r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
}

class Session {
  _id;
  _model;
  _think;
  _connection;
  _toolDefs;

  history = [];
  tools = [];
  get id() { return this._id; }
  get model() { return this._model; }
  get think() { return this._think; }
  get connection() { return this._connection; }
  
  get toolDefinitions() {
    if (this.tools && this.tools.length > 0 && this._toolDefs) {
      return this.tools.map(toolName => this._toolDefs[toolName]);
    }
    return [];
  }
  
  constructor(props) {
    this._id = props.id || ID();
    this._model = props.model;
    this._think = props.think || false;
    this._connection = props.connection;
  }
  
  async handleTool(toolCall) {
    let id = toolCall.id;
    let name = toolCall.function.name;
    let args = toolCall.function.arguments;
    let output;
    
    if (this.tools.includes(name) && name in this._toolDefs) {
      let tool = this._toolDefs[name];
      output = await tool.run(args);
    } else {
      output = `Error: tool "${name}" not found!`;
    }
    
    return { id, tool_name: name, content: output };
  }
  
  async send_internal(messages)  {
    let payload = {
      model: this.model,
      think: false, // TODO
      stream: false, // TODO
      messages: messages,
      tools: [] // TODO
    };

    let response = await fetch(this.connection, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
      // TODO
      // signal: abortSignal
      // Somewhere else, make an AbortController whose c.signal we pass here.
      // Use c.abort() to cancel this request.
    });

    // TODO: blindly assumes success
    let responseJson = await response.text();
    return JSON.parse(responseJson);
  }
  
  async send(outgoing) {
    this.history.push(outgoing);

    let responseObj = await this.send_internal(this.history);
    
    while (responseObj.tool_calls) {
      let results = await Promise.all(responseObj.tool_calls.map(t => this.handleTool(t)));
      let messages = results.forEach(r => r.role = 'tool');
      this.history.push(messages[0]);
      responseObj = await this.send_internal(this.history);
    }

    // TODO: responseObj has other cool stuff in it that I want to use later:
    // - prompt_eval_count (tokens up)
    // - eval_count (tokens down)
    // - prompt_eval_duration / eval_duration / total_duration
    let incoming = responseObj.message;

    this.history.push(incoming);
    return incoming;
  }
}


async function repl() {
  let session = new Session({
    model: CONFIG.model,
    connection: CONFIG.connection
  });
  terminal.Text.color('bold', `Started session ${session.id}.\n`);
  while (true) {
    let userInput = await rl.question('❯ ');
    console.log(); // newline
    
    if (userInput[0] === '!' || userInput[0] === '/') {
      // shell command or slash command
      console.log('Shell & slash commands not yet implemented.');
    } else {
      let userMessage = { role: 'user', content: userInput };
      let modelMessage = await session.send(userMessage);

      if (modelMessage.content) {
        console.log(marked.parse(modelMessage.content));
      } else {
        console.log('No message content, dumping JSON:\n', JSON.stringify(modelMessage));
      }
    }

    console.log();
  }
}

repl();