const fs = require('node:fs');

const ID = () => {
  // SLOP: generated by asking for a "unique identifier like a guid"
  return 'xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx'.replace(/[xy]/g, function (c) {
    let r = Math.random() * 16 | 0, v = c == 'x' ? r : (r & 0x3 | 0x8);
    return v.toString(16);
  });
};

class SimpleLogger {
  #stream;
  constructor(path, flags) {
    this.#stream = fs.createWriteStream(path, { flags: flags || 'w' });
  }
  log(x) {
    let s; 
    if (typeof x === 'string') {
      s = x;
    } else {
      x = JSON.stringify(x);
    }
    this.#stream.write(x + '\n');
  }
};
const Logger = new SimpleLogger('debug.log');

module.exports = { ID, Logger };